

PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS MARCA;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS COMPRA;
DROP TABLE IF EXISTS ESTOQUE;
DROP TABLE IF EXISTS SAIDA;

CREATE TABLE DEPARTAMENTO(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(521)
);
CREATE TABLE MARCA(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(521),
    EMPRESA VARCHAR(521)
);
CREATE TABLE PRODUTO(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(521),
    ID_MARCA INTEGER NOT NULL,
    ID_DEPT INTEGER NOT NULL,
	FOREIGN KEY(ID_MARCA) REFERENCES MARCA(ID),
	FOREIGN KEY(ID_DEPT) REFERENCES DEPARTAMENTO(ID)
);
CREATE TABLE COMPRA(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    PRECO DOUBLE,
    DT DATE,
	QUANTIDADE INTEGER NOT NULL,
	TOTAL INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID)
);

CREATE TABLE SAIDA(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DT DATE,
	QUANTIDADE INTEGER NOT NULL,
    ID_COMPRA INTEGER NOT NULL,
	ID_PRODUTO INTEGER NOT NULL,
	FOREIGN KEY(ID_COMPRA) REFERENCES COMPRA(ID),
	FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID)
);
